name: code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync

      - name: ruff check
        run: uv run ruff check

      - name: mypy check
        run: uv run mypy .
